config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy'
  end     
  resources :tags
  resources :training_resources
  #get 'training/TrainingResources'
  get 'training/MoreResources'
  root 'training#TrainingResources'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :training_resources
end

app/models/training_resource.rb
class TrainingResource < ApplicationRecord
    has_one_attached :image
    has_many_attached :pictures
    has_rich_text :body
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit 
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:tag)
    end
end

app/controllers/training_controller.rb
class TrainingController < ApplicationController
  def TrainingResources
  end

  def MoreResources
  end
  
end

app/controllers/training_resources_controller.rb
class TrainingResourcesController < ApplicationController
  before_action :set_training_resource, only: %i[ show edit update destroy ]

  # GET /training_resources or /training_resources.json
  def index
    @tags =Tag.all
    tag = params[:tag]

    if !tag.nil?
      @training_resources = TrainingResource.where(:tag_id => tag)
    else
      @training_resources = TrainingResource.all
    end
  end

  # GET /training_resources/1 or /training_resources/1.json
  def show
  end

  # GET /training_resources/new
  def new
    @training_resource = TrainingResource.new
  end

  # GET /training_resources/1/edit
  def edit
  end

  # POST /training_resources or /training_resources.json
  def create
    @training_resource = TrainingResource.new(training_resource_params)

    respond_to do |format|
      if @training_resource.save
        format.html { redirect_to training_resource_url(@training_resource), notice: "Training resource was successfully created." }
        format.json { render :show, status: :created, location: @training_resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @training_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /training_resources/1 or /training_resources/1.json
  def update
    respond_to do |format|
      if @training_resource.update(training_resource_params)
        format.html { redirect_to training_resource_url(@training_resource), notice: "Training resource was successfully updated." }
        format.json { render :show, status: :ok, location: @training_resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @training_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_resources/1 or /training_resources/1.json
  def destroy
    @training_resource.destroy!

    respond_to do |format|
      format.html { redirect_to training_resources_url, notice: "Training resource was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training_resource
      @training_resource = TrainingResource.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def training_resource_params
      params.require(:training_resource).permit(:Author, :Title, :image, :Short_description, :Long_description, :tag_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/training_helper.rb
module TrainingHelper
end

app/helpers/training_resources_helper.rb
module TrainingResourcesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LifeChurch App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="footer.css">
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  
  <%= render 'training/header' %>
  <div class ="container">
  <br/>

    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

      <%= yield %>
  </div>

  

  <br/>
  <% render 'training/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="dropdown">
    <% form.label :tag, style: "display: block" %>
    <%= form.text_field :tag, class:"form-control", placeholder:"Tag" %>
  </div> <br/>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Tag:</strong>
    <%= tag.tag %>
  </p>

</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<h1>Tags</h1>

<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag", tag %>
    </p>
  <% end %>
</div>

<%= link_to "New tag", new_tag_path, class: "btn btn-primary" %>

app/views/tags/new.html.erb
<div class="container-fluid mt-3">

<h1>Create New Tag</h1>


<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Back to tags", tags_path %>
</div>

</div>

app/views/tags/show.html.erb
<%= render @tag %>

<div>
  <%= link_to "Edit this tag", edit_tag_path(@tag) %> |
  <%= link_to "Back to tags", tags_path %> <br/><br/>

  <%= button_to "Destroy this tag", @tag, method: :delete, class: "btn btn-danger" %> 
</div>

app/views/training/MoreResources.html.erb
<h1>About US...</h1>

app/views/training/TrainingResources.html.erb
<h1>Home Sweet Home!</h1>

<p>Everytime you here know that you have the persmission to relax because you are Home!!<p/>
  

app/views/training/_footer.html.erb
<footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>My Footer</p>
        <p>New Life Church Register Here.</p>
      </div>
    </footer>

app/views/training/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  <%= link_to 'Life.Church App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'Resources', training_resources_path, class:"nav-link active" %>
      </li>
    <% if user_signed_in? %>

     <li class="nav-item">
      <%= link_to 'Add Resources', new_training_resource_path, class:"nav-link active" %>
    </li>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true }, class:"nav-link" %>
        </li>
    <li class="nav-item">
    <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link active" %>
    </li>
    <% else %>

    <li class="nav-item">
    <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link active" %>
  </li>
  <li class="nav-item">
  <%= link_to 'Sign In', new_user_session_path, class:"nav-link active" %>
</li>
<%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/training_resources/_form.html.erb
<%= form_with(model: training_resource) do |form| %>
  <% if training_resource.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(training_resource.errors.count, "error") %> prohibited this training_resource from being saved:</h2>

      <ul>
        <% training_resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :Author, class:"form-control", placeholder:"Author" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :Title, class:"form-control", placeholder:"Title" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :Short_description, class:"form-control", placeholder:"Short Description" %>
  </div>

  <div class="mb-3">
    <%= form.text_area :Long_description, class:"form-control", placeholder:"Long Description" %>
  </div>

  <div class="mb-3">
    <%= form.file_field :image, class:"form-control", placeholder:"Image" %>
  </div>

  <div class="dropdown">
  <strong><%= form.label :Tag %></strong>
    <%= form.select :tag_id, Tag.all.map {|t| [t.tag, t.id]}%> 
  </div>
  <br/>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>

  <% form.submit "Create Resource", class: "btn btn-primary" %>
    <% link_to "Back", training_resources_path, class:"btn btn-dark" %>
<% end %>

app/views/training_resources/_training_resource.html.erb
<div id="<%= dom_id training_resource %>">
  <p>
    <strong>Author:</strong>
    <%= training_resource.Author %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= training_resource.Title %>
  </p>

  <p>
    <strong>Short description:</strong>
    <%= training_resource.Short_description %>
  </p>

  <p>
    <strong>Long description:</strong>
    <%= training_resource.Long_description %>
  </p>

</div>

app/views/training_resources/edit.html.erb
<div class="container-fluid mt-3">

<h1>Editing training resource</h1>

<br/>
<%= render "form", training_resource: @training_resource %>

<br/>

  <%= link_to "Show Resource", @training_resource, class: "btn btn-primary" %> 
  <%= link_to "Back", training_resources_path, class:"btn btn-dark" %>

</div>

app/views/training_resources/index.html.erb
<div class="container">
 <h1>Training Resources</h1>
    <div class="row">

    
    <div class="col-md-8">

    <div class="row">
    
   
     <% @training_resources.each do |training_resource| %>
        <div class="col-md-6">
            <div class="card mt-3">
                <div class="card-body">
                                    <h3><%= link_to training_resource.Title, training_resource_path(training_resource.id) %></h3>
            <%= link_to "View", training_resource_path(training_resource.id), class:"btn btn-primary"%>
                </div>
            </div>
            
        </div>
                <% end %>

                 </div>
    </div>

    

    <div class="col-md-4">


    <div class="card mt-3">
        <div class="card-header">
            <strong>Tags</strong>
        </div>

        <div class="card-body">

        <ul class="list-group">

         <% @tags.each do |tag| %>

        
  <li class="list-group-item d-flex justify-content-between align-items-center">
               <%= link_to tag.tag, training_resources_path(:tag => tag.id) %>

    <span class="badge badge-primary badge-pill"><%= tag.training_resources.count %></span>
  </li>
       <% end %>

        </ul>
        </div><br/>
            <%= link_to "Create New tag", new_tag_path, class: "btn btn-primary" %>
    
    </div>
     
    </div>
     
       
 </div>

 
    </div> <br/>


</div>

app/views/training_resources/new.html.erb
<div class="container-fluid mt-3">
<h1>Add training resource</h1>

<br/>
<%= render "form", training_resource: @training_resource %>


<div>
  <%= link_to "Back", training_resources_path, class:"btn btn-dark" %>
</div>

</div>

app/views/training_resources/show.html.erb
<div class="container-fluid mt-3">
<%= render @training_resource %>


<% if @training_resource.image.attached? %>
<%= image_tag @training_resource.image, width: "200px" %> <br/><br/>
<%end%>
<p><b>Tag:</b> <%= @training_resource.tag.tag %></p>

<%= link_to "Edit Resource", edit_training_resource_path(@training_resource.id), class: "btn btn-primary", style: "margin-right: 20px"%>
  <%= link_to "Back", training_resources_path, class:"btn btn-dark" %> <br/> <br/>
  <%= button_to "Delete", @training_resource, method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, class: "btn btn-danger" %>

</div>